issue 141
modcluster/docs.modcluster.io pull request #144
Opened 2023-11-10 11:36 UTC by jajik

2023-11-13 15:17 UTC, jajik commented
I think it's in a mergeable state, but once we releaase mod_proxy_cluster 2.0, I believe it would be worth it redoing the documentation a bit (there is duplication of information, we could then drop 1.3.x schism, update examples, ...). But that's for sometime in the future...

2023-11-29 11:17 UTC, rhusar requested changes

2023-11-29 11:17 UTC, rhusar commented on docs/src/main/asciidoc/native.adoc
> +NOTE: *Older mod_cluster versions:* Versions older than 1.3.1 only accept values 0 and 1 respectively.
This change is wrong, the release name is indeed 1.3.1.Final

https://github.com/modcluster/mod_cluster/tree/1.3.1.Final?search=1
https://github.com/modcluster/mod_cluster/blob/1.3.1.Final/native/include/mod_proxy_cluster.h#L31
https://github.com/modcluster/mod_cluster/blob/1.3.1.Final/pom.xml#L33

2023-12-08 10:39 UTC, rhusar approved these changes
LGTM

2023-12-08 10:39 UTC, merged

2023-12-08 10:39 UTC, rhusar commented
Thanks @jajik