Fix load-balancing demo application paths
modcluster/docs.modcluster.io pull request #145
Opened 2023-11-13 15:00 UTC by jajik

The demo application seems working with a few tweaks.

ref #141

2023-11-13 15:26 UTC, rhusar requested changes

2023-11-13 15:26 UTC, rhusar commented on docs/src/main/asciidoc/demo.adoc
> -WARNING: The demo application has not been recently updated and might not work with newer software versions as described below!
Actually this is what I added last week :-D

Are you saying it works no problem on WildFly? I doubt it!

2023-11-13 15:30 UTC, jajik commented on docs/src/main/asciidoc/demo.adoc
> -WARNING: The demo application has not been recently updated and might not work with newer software versions as described below!
Hm, sorry, I was a bit fast with the removal. I'll add it back.

Tomcat (8.5, 9) works.

Thanks for the catch.

2023-11-13 15:34 UTC, jajik commented on docs/src/main/asciidoc/demo.adoc
> -WARNING: The demo application has not been recently updated and might not work with newer software versions as described below!
(Thinking about it, I honestly don't know why I separated this from #144...)

2023-11-13 15:38 UTC, rhusar commented on docs/src/main/asciidoc/demo.adoc
> -WARNING: The demo application has not been recently updated and might not work with newer software versions as described below!
Right, old tomcats should work ,but anything jakarta, nope..

2023-11-22 13:04 UTC, rhusar approved these changes

2023-11-22 13:05 UTC, merged

2023-11-22 13:05 UTC, rhusar commented
The demo should be moved out of the main repo anyway, so we will update this even more then.