Rewrite ModCluster Management Protocol section
modcluster/docs.modcluster.io pull request #208
Opened 2024-09-11 14:12 UTC by jajik

@jfclere  @rhusar  There is some space for an improvement, so I'm opening this as a draft. However, if you'd like to chime in, feel free to.

2024-09-13 08:57 UTC, jajik commented
Ready for reviews.

2024-09-13 08:59 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| PING-RSP     | Response to PING
I think all these -RSP messages, these don't exist nowhere, correct?

2024-09-13 09:05 UTC, jajik commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| PING-RSP     | Response to PING
No, or more precisely these are only values of `Type` field in response to the corresponding command (instead of request method as for the non-RSP counterparts).

2024-09-13 09:10 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> +NOTE: All parameter names are case insensitive, but their values are NOT.
So did you confirm this for undertow and mod_proxy_cluster impls?

2024-09-13 09:38 UTC, jajik commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> +NOTE: All parameter names are case insensitive, but their values are NOT.
I did for mod_proxy_cluster (well, I haven't test *all* possible cases, but at this point it would be a bug). For undertow, I went through the code only.

2024-09-13 10:20 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| PING-RSP     | Response to PING
That's what I though, thanks for fixing this

2024-09-13 10:20 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> +NOTE: All parameter names are case insensitive, but their values are NOT.
Sounds good

2024-09-17 10:55 UTC, rhusar requested changes

2024-09-17 10:55 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| Maxattempts | TODO | TODO | TODO
Wait, where did these go?

2024-09-20 14:06 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| Maxattempts | TODO | TODO | TODO
These are emitted here FYI - https://github.com/modcluster/mod_cluster/blob/main/core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPRequestFactory.java#L75-L131

2024-09-24 08:45 UTC, jfclere approved these changes

2024-09-27 09:35 UTC, jajik commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| Maxattempts | TODO | TODO | TODO
This was moved under this comment https://github.com/modcluster/docs.modcluster.io/pull/208/files#diff-a94052d80956b36ac6172a771abee543bc86099820784be22f24f1f03ed709c9R123

I don't think we want to duplicate it here because I don't think we won't be able to keep it up to date. It just sends the values of these directives/settings described elsewhere...

2024-09-27 12:02 UTC, jajik commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| Maxattempts | TODO | TODO | TODO
Well, at least we agree that things are unclear. I'll look at it more on Monday.

2024-09-27 12:30 UTC, rhusar commented on docs/src/main/asciidoc/developer/management_protocol.adoc
> -| Maxattempts | TODO | TODO | TODO
OK

2024-09-27 12:30 UTC, rhusar approved these changes
LGTM with exception discussed above - split that into https://github.com/modcluster/docs.modcluster.io/issues/211

2024-09-27 12:31 UTC, merged

2024-09-27 12:31 UTC, rhusar commented
@jajik Thanks for the cleanup, I have split out the parameters issue into https://github.com/modcluster/docs.modcluster.io/issues/211.